### ISSUE TITLE
Setup Codecov

### ISSUE THREAD

**Issue by lucasrcezimbra** [lucasrcezimbra/missas.com.br#82]
```yaml
- name: Upload coverage reports to Codecov
    uses: codecov/codecov-action@v5
    with:
      token: ${{ secrets.CODECOV_TOKEN }}
```
